doc.type html
script
html
head
utf8
viewport content=width=device-width, initial-scale=one
title covid strings11 first round bracket
div id bracket class bracket div
script src bracket.js
link rel= stylesheet href=css
head
body
bracket-container{}
matchup
solid zero;
padding 
text align center 
filename=covid strings11 first round.js
first round =(highest overall seed, second highest seed, third highest seed, fourth highest seed,fifth highest seed,third low seed, second low seed,lowest overall seed)
highest overall seed = seed1
second highest seed=seed2
third highest seed=seed3
firstmiddleseed=seed4
second middle seed = seed5
third lowest seed= seed6
second lowest seed = seed7
lowest overall seed = seed8
addeventlistener(domcontentloaded, () => {
bracket =getelementbyid(bracket);
matchup1=(violet relivers versus black night riders)
matchup2=(purple bravehearts versus turquoise waves)
matchup3=(orange rna messengers versus burgundy rebuilders)
matchup4=(teal terminators versus white transit angels )
matchup div=matchup
document.createelement 
matchupdiv.classname=(matchup)
matchupdiv.innerHTML =[matchup]
rounddiv.appendchild(matchup)
matchup toggle code
if (event.target.classlist.contains(team)) 
return matchup
else 
add matchup
for (i in covid strings first round)
round div=create element
round div class name=covid strings11 first round
bracket.appendchild(round div)
if (event.target.covid strings seed list.contains(matchup))
return matchup
else:
add matchup
java util.scanner
java.util
questions[]questions={
question1
question2
question3
question4
question5
question6
question7
question8
question9
question10
question11
question12
question13
question14
if selectedanswer==correct:
return true
if selectedanswer=incorrect
return false
advancingteam=slice(current teams)
result=declarewinner(matchup1)
if black score>=forty:
console.log(black night riders win)
else:
console.log(violet relivers win)
result=declarewinner(matchup2)
if turquoise score>=forty:
console.log(turquoise waves win)
else:
console.log(purple bravehearts win)
result=declarewinner(matchup3)
if burgundy score>=forty:
console.log(burgundy rebuilders win)
else:
console.log(orange rna messengers win)
result=declarewinner(matchup4)
if white score>=forty:
console.log(white transit angels win)
else:
console.log(teal terminators win)
return filename
