doc.type html
html lang en 
script
header=document create.element(header)
header.style.backgroundcolor=#4caf50
header.style.color=’white’
header.style.padding=’10px’
header.style.textalign=’center’
header.style.text.fontsize=’24px’
header.textcontent=’covid strings 11’ 
document appendchild(header)
<header.html>
heading variables 
the heading numbers that determine where each heading and subheading go 
heading1=#background overview
heading2=#functions
heading3=background code 
<header.html>
background overview
background for covid strings11
filename=covid strings11 background .js
java.awt graphics
this.img=document.createelement(covid)
img.src=http://www.google.com/intl/en_com/images/logo_plain.png
src=document getelementbyid(header)
src.appendchild(this.img)
<div id=header></div>
audio=new audio(audio_file mp3)
audio.play 
random button
new button (set random color)
option button
new button (change color)
public fun with graphics()
color panel=new jpanel();
add (panel, center )
new panel (center)
buttonpanel.add(randombutton);
random.button add actionlistener(new action listener)
override 
public actionperformed(actionevent e)
random r= newrandom();
<header.html>
background functions 
functions used in covid strings11 background 
colorpanel.setbackground(rnextint(thirteen),)(rnextint(thirteen),)(rnextint(thirteen),)(rnextint(thirteen),)(rnextint(thirteen),)(rnextint(thirteen),)(rnextint(thirteen),)(rnextint(thirteen)))(rnextint(thirteen)))(rnextint(thirteen)))(rnextint(thirteen)))(rnextint(thirteen)))(rnextint(thirteen)))
buttonpanel.add(optionbutton);
optionbutton.add actionlistener(new action listener)
override 
<header.html>
background code 
code to program game background
public actionperformed(actionevent e)
random r= newrandom();
setbackground
add(optionbutton);
actionlistener(new action listener)
override 
color m=jcolorchooser.showdialog(funwithgraphics.this)
if(multi!=null)
color panel set.background(multi)
this.add(buttonpanel,borderlayout.south)
public static main(string []args)
jframe f=new covid strings11()
set title(covid strings11)
set default closeoperation(exit_on_close);
setsize
set visible(true);
<label id=lblscore>zero</label>
score=zero
if (mult == x*y)
[non-concatenated]
score+=ten
else:
score-=ten
if (mult == x*y)
[concatenated]
score+=twenty
else:
score-=twenty
lblscore=getelementbyid(score)
score.innerhtml=score
public actionperformed(action event e) 
print (next button clicked)
add(next button);
frame set visible true
object {a:one, b:two, c:three, d:four, e:five, f:six, g:seven, h:eight}
keys object (team)
entries object (obj);
value object= [team color]
return filename
